language: node_js
before_install: npm install -g grunt-cli
sudo: required
services:
  - docker
before_script:
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD -e $DOCKER_HUB_EMAIL
after_success:
  - make all-the-dockers
  - make docker-push
